#!/usr/bin/env python3
from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')


def rep(old: str, new: str):
    global s
    if old not in s:
        raise SystemExit('Trecho não encontrado para atualização:\n' + old[:220])
    s = s.replace(old, new, 1)

rep('PILOTO v0.10 web', 'PILOTO v0.11 web')

css = r'''
.money-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.money-summary .record b{font-size:20px;display:block}.money-controls{display:grid;grid-template-columns:180px 260px;gap:8px;margin:10px 0 14px}.money-controls select{padding:10px;border:1px solid var(--line);border-radius:10px;background:#fff;font-size:14px}.donut-layout{display:grid;grid-template-columns:240px 1fr;gap:20px;align-items:center;margin:12px 0 18px}.donut{width:220px;height:220px;border-radius:50%;position:relative;margin:auto}.donut-hole{position:absolute;inset:44px;border-radius:50%;background:var(--card);display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:10px;border:1px solid var(--line)}.donut-hole b{font-size:18px}.donut-hole span{font-size:11px;color:var(--muted)}.legend{display:grid;gap:7px}.legendrow{display:grid;grid-template-columns:12px minmax(0,1fr) auto;gap:8px;align-items:center;font-size:12px}.legenddot{width:10px;height:10px;border-radius:3px}.trend{display:grid;gap:8px;margin:10px 0 14px}.trendrow{display:grid;grid-template-columns:60px minmax(120px,1fr) 120px;gap:9px;align-items:center;font-size:12px}.trendbar{height:18px;background:var(--soft);border-radius:5px;overflow:hidden;display:flex}.trendbar i{height:100%;display:block}.trendbar .ceaps{background:#202a44}.trendbar .fora{background:#7f9c84}.trendlegend{display:flex;gap:15px;flex-wrap:wrap;font-size:11px;color:var(--muted);margin-bottom:8px}.trendlegend i{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;vertical-align:-1px}.cat-table td:first-child{width:58%}.source-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 18px}@media(max-width:800px){.money-summary{grid-template-columns:1fr}.money-controls,.donut-layout,.trendrow{grid-template-columns:1fr}.donut{width:190px;height:190px}.donut-hole{inset:38px}.trendrow{gap:4px}.trendrow>.money{text-align:left}.legendrow{grid-template-columns:12px minmax(0,1fr) auto}}
'''
rep('</style>', css + '</style>')

rep(" const [parts,atual,historico,amostra]=await Promise.all([\n  Promise.all(files.map(f=>fetch(f,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Base não encontrada: '+f);return r.text()}))),\n  getJSON('dados/votacoes_senado.json'),getJSON('dados/votacoes_senado_historico.json'),getJSON('dados/validacao_amostra_votacoes_2019_2025.json',false)\n ]);",
" const [parts,atual,historico,amostra,gastos]=await Promise.all([\n  Promise.all(files.map(f=>fetch(f,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Base não encontrada: '+f);return r.text()}))),\n  getJSON('dados/votacoes_senado.json'),getJSON('dados/votacoes_senado_historico.json'),getJSON('dados/validacao_amostra_votacoes_2019_2025.json',false),getJSON('dados/gastos_mandato_senado.json')\n ]);")

rep(" if(historico.escopo!=='historico_fechado'||!Array.isArray(historico.votacoes)||historico.votacoes.length<1000)throw Error('Base histórica 2019–2025 em formato inesperado');",
" if(historico.escopo!=='historico_fechado'||!Array.isArray(historico.votacoes)||historico.votacoes.length<1000)throw Error('Base histórica 2019–2025 em formato inesperado');\n if(gastos.escopo!=='gastos_mandato_senado'||!Array.isArray(gastos.por_ano)||gastos.por_ano.length<8)throw Error('Base de gastos do mandato em formato inesperado');")

rep(" D.votacoes_meta={inicio:2019,fim:2026,total:D.votacoes_nominais.length,historico_quantidade:historico.quantidade,duplicados_historico:historico.duplicados_removidos,atual_quantidade:atual.quantidade,atualizado_em_utc:atual.atualizado_em_utc,validacao_atual:atual.validacao,amostra};\n return D;",
" D.votacoes_meta={inicio:2019,fim:2026,total:D.votacoes_nominais.length,historico_quantidade:historico.quantidade,duplicados_historico:historico.duplicados_removidos,atual_quantidade:atual.quantidade,atualizado_em_utc:atual.atualizado_em_utc,validacao_atual:atual.validacao,amostra};\n D.gastos_mandato_oficial=gastos;\n return D;")

helpers = r'''
const EXPENSE_COLORS=['#202a44','#3e5c76','#6f8faa','#7f9c84','#b08b57','#8d6a9f','#b85c5c','#5d7a6f'];
function donutHtml(items,total,label){const nz=(items||[]).filter(x=>Number(x.valor)>0).sort((a,b)=>b.valor-a.valor);if(!nz.length||!total)return '<div class="muted">Sem valores para esta seleção.</div>';let cur=0;const stops=nz.map((x,i)=>{const a=cur,b=cur+(Number(x.valor)/total)*360;cur=b;return `${EXPENSE_COLORS[i%EXPENSE_COLORS.length]} ${a.toFixed(2)}deg ${b.toFixed(2)}deg`});const legend=nz.map((x,i)=>`<div class="legendrow"><span class="legenddot" style="background:${EXPENSE_COLORS[i%EXPENSE_COLORS.length]}"></span><span>${esc(x.categoria)}</span><span>${money(x.valor)} · ${(100*x.valor/total).toFixed(1).replace('.',',')}%</span></div>`).join('');return `<div class="donut-layout"><div class="donut" role="img" aria-label="Composição das despesas por categoria" style="background:conic-gradient(${stops.join(',')})"><div class="donut-hole"><b>${money(total)}</b><span>${esc(label)}</span></div></div><div class="legend">${legend}</div></div>`}
function expenseTrendHtml(rows){const max=Math.max(...rows.map(r=>Number(r.total_mostrado)||0),1);return `<div class="trendlegend"><span><i style="background:#202a44"></i>CEAPS</span><span><i style="background:#7f9c84"></i>Gastos fora da CEAPS exibidos pelo Senado</span></div><div class="trend">${rows.map(r=>{const a=100*r.total_ceaps/max,b=100*r.total_fora_ceaps/max;return `<div class="trendrow"><b>${r.ano}${r.parcial?'*':''}</b><div class="trendbar" title="${money(r.total_mostrado)}"><i class="ceaps" style="width:${a}%"></i><i class="fora" style="width:${b}%"></i></div><div class="money">${money(r.total_mostrado)}</div></div>`}).join('')}</div>`}
function expenseRowsTable(items,total){const rows=(items||[]).slice().sort((a,b)=>b.valor-a.valor);return `<table class="cat-table"><thead><tr><th>Categoria</th><th>Valor</th><th>Participação</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.categoria)}</td><td class="money">${money(x.valor)}</td><td>${total?`${(100*x.valor/total).toFixed(1).replace('.',',')}%`:'—'}</td></tr>`).join('')}</tbody></table>`}
'''
rep('function render(D){', helpers + '\nfunction render(D){')

rep(" const p=D.politico,V=D.votacoes_nominais||[],E=D.emendas_carregadas||[],R=D.registros||[],F=D.fin||[],G=D.gastos_mandato||[],VM=D.votacoes_meta||{};",
" const p=D.politico,V=D.votacoes_nominais||[],E=D.emendas_carregadas||[],R=D.registros||[],F=D.fin||[],G=D.gastos_mandato||[],GO=D.gastos_mandato_oficial||null,VM=D.votacoes_meta||{};")

start = s.index(" const areas=Object.entries(er.por_area||{});")
end = s.index(" const cats=F.filter", start)
money_block = r''' const areas=Object.entries(er.por_area||{});
 if(GO&&Array.isArray(GO.por_ano)){
  document.getElementById('dinheiro').innerHTML=`<h2>Dinheiro público</h2><div class="notice oknote"><b>Gastos do mandato no Senado — 2019 a 2026.</b> Valores coletados diretamente da API oficial do Senado e atualizados automaticamente. O ano de 2026 é parcial. A soma mostrada abaixo reúne CEAPS e os gastos não inclusos na CEAPS exibidos nessa página do Senado; <b>não representa o custo integral do mandato</b> e não inclui, por exemplo, folha de pessoal ou subsídio do senador.</div><div class="money-summary"><div class="record"><span class="source">CEAPS no período</span><b>${money(GO.total_ceaps_periodo)}</b></div><div class="record"><span class="source">Fora da CEAPS exibidos</span><b>${money(GO.total_fora_ceaps_periodo)}</b></div><div class="record"><span class="source">Soma das duas seções</span><b>${money(GO.total_mostrado_periodo)}</b></div></div><div class="source">Atualizado em ${esc(fmtDateTime(GO.atualizado_em_utc))}. *2026 parcial e sujeito a ajustes, estornos ou novos lançamentos.</div><h3>Evolução anual dos recursos exibidos</h3>${expenseTrendHtml(GO.por_ano)}<h3>Composição por categoria</h3><div class="money-controls"><select id="expenseYear"><option value="periodo">Período 2019–2026</option>${GO.por_ano.slice().reverse().map(x=>`<option value="${x.ano}">${x.ano}${x.parcial?' (parcial)':''}</option>`).join('')}</select><select id="expenseGroup"><option value="ceaps">CEAPS</option><option value="fora">Gastos fora da CEAPS exibidos</option></select></div><div id="expenseChart"></div><div id="expenseTable"></div><div id="expenseSource" class="source-actions"></div><h3>Emendas parlamentares carregadas</h3><div class="notice">As emendas abaixo ainda são uma amostra e não representam o total destinado no mandato.</div><p><b>Empenhado na amostra:</b> ${money(er.empenhado)} · <b>Pago na amostra:</b> ${money(er.pago)}</p><h3>Por área — amostra de emendas</h3><table><tbody>${areas.map(([a,x])=>`<tr><td>${esc(a)}</td><td>${x.qtd} registro(s)</td><td class="money">${money(x.empenhado)}</td><td class="money">${money(x.pago)}</td></tr>`).join('')}</tbody></table><h3>Emendas carregadas</h3><table><tbody>${E.map(e=>`<tr><td>${e.ano}</td><td><b>${esc(e.funcao)}</b><br><span class="source">${esc(e.descricao)}</span></td><td>${esc(e.localidade)}</td><td class="money">${money(e.empenhado)}</td><td class="money">${money(e.pago)}</td><td><a href="${esc(e.url)}" target="_blank" rel="noopener">Fonte</a></td></tr>`).join('')}</tbody></table>`;
  const renderExpense=()=>{const y=document.getElementById('expenseYear').value,g=document.getElementById('expenseGroup').value;let items,total,label,source='https://www12.senado.leg.br/dados-abertos/administrativo/senadores/cotas-para-exercicio-da-atividade-parlamentar';if(y==='periodo'){items=g==='ceaps'?GO.agregado_ceaps:GO.agregado_fora_ceaps;total=g==='ceaps'?GO.total_ceaps_periodo:GO.total_fora_ceaps_periodo;label=(g==='ceaps'?'CEAPS':'Fora da CEAPS')+' · 2019–2026'}else{const row=GO.por_ano.find(x=>String(x.ano)===y);items=g==='ceaps'?row.ceaps:row.fora_ceaps;total=g==='ceaps'?row.total_ceaps:row.total_fora_ceaps;label=(g==='ceaps'?'CEAPS':'Fora da CEAPS')+' · '+y+(row.parcial?' parcial':'');source=row.fonte_visual}document.getElementById('expenseChart').innerHTML=donutHtml(items,total,label);document.getElementById('expenseTable').innerHTML=expenseRowsTable(items,total);document.getElementById('expenseSource').innerHTML=`<a class="btn" href="${esc(source)}" target="_blank" rel="noopener">Abrir fonte oficial do Senado</a>`};
  document.getElementById('expenseYear').onchange=renderExpense;document.getElementById('expenseGroup').onchange=renderExpense;renderExpense();
 }else{
  document.getElementById('dinheiro').innerHTML=`<h2>Dinheiro público</h2><div class="notice">Base oficial de gastos do mandato indisponível nesta carga.</div>`;
 }
'''
s = s[:start] + money_block + s[end:]

old_ask = "else if(/emenda|recurso|dinheiro publico/.test(n)){html=`Há <b>${E.length}</b> emendas carregadas nesta amostra, com ${money(er.empenhado)} empenhados e ${money(er.pago)} pagos. A amostra ainda não representa o total do mandato.`}"
new_ask = r'''else if(/gasto|gastos|ceaps|cota parlamentar|correios|aluguel|passagens|locomocao|hospedagem|combustivel|divulgacao/.test(n)&&GO?.por_ano?.length){const year=(n.match(/\b(2019|2020|2021|2022|2023|2024|2025|2026)\b/)||[])[1];const row=year?GO.por_ano.find(x=>String(x.ano)===year):null;const cats=row?[...row.ceaps,...row.fora_ceaps]:[...GO.agregado_ceaps,...GO.agregado_fora_ceaps];const keys=['correios','aluguel','passagens','locomocao','hospedagem','combustivel','divulgacao','material','apoio','seguranca','impulsionamento','diarias'];const wanted=keys.filter(k=>n.includes(k));const hits=wanted.length?cats.filter(x=>wanted.some(k=>strip(x.categoria).includes(k))):[];if(hits.length){const total=hits.reduce((a,x)=>a+x.valor,0);html=`${year?`Em ${year}`:'No período 2019–2026'}, encontrei ${hits.length} categoria(s) correspondente(s), somando <b>${money(total)}</b>:`+hits.map(x=>`<div class="answeritem"><b>${esc(x.categoria)}</b> — ${money(x.valor)}</div>`).join('')+(row?`<div style="margin-top:6px"><a href="${esc(row.fonte_visual)}" target="_blank" rel="noopener">Fonte oficial do Senado</a></div>`:'')}else if(row){html=`Em <b>${year}</b>${row.parcial?' (parcial)':''}: CEAPS ${money(row.total_ceaps)}, gastos fora da CEAPS exibidos ${money(row.total_fora_ceaps)}, soma das duas seções ${money(row.total_mostrado)}. <a href="${esc(row.fonte_visual)}" target="_blank" rel="noopener">Fonte oficial do Senado</a>`}else{html=`No período 2019–2026: CEAPS <b>${money(GO.total_ceaps_periodo)}</b>, gastos fora da CEAPS exibidos <b>${money(GO.total_fora_ceaps_periodo)}</b>, soma das duas seções <b>${money(GO.total_mostrado_periodo)}</b>. Isso não representa o custo integral do mandato; veja a aba Dinheiro público.`}}else if(/emenda|recurso|dinheiro publico/.test(n)){html=`Há <b>${E.length}</b> emendas carregadas nesta amostra, com ${money(er.empenhado)} empenhados e ${money(er.pago)} pagos. A amostra ainda não representa o total do mandato.`}'''
rep(old_ask, new_ask)

p.write_text(s, encoding='utf-8')
print('v0.11 aplicada ao index.html')
